// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VYPS.Domain2;

#nullable disable

namespace VYPS.Domain2.Migrations
{
    [DbContext(typeof(VYPSContext))]
    partial class VYPSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VYPS.Model2.Models.Aka_Ders", b =>
                {
                    b.Property<int>("akaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("akaId"), 1L, 1);

                    b.Property<int>("dkod")
                        .HasColumnType("int");

                    b.Property<int>("pkod")
                        .HasColumnType("int");

                    b.HasKey("akaId");

                    b.HasIndex("dkod");

                    b.HasIndex("pkod");

                    b.ToTable("Aka_Ders");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Akademik", b =>
                {
                    b.Property<int>("pkod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pkod"), 1L, 1);

                    b.Property<string>("padi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("psoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sicilNo")
                        .HasColumnType("int");

                    b.HasKey("pkod");

                    b.ToTable("Akademiks");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Bolumler", b =>
                {
                    b.Property<int>("bolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bolumId"), 1L, 1);

                    b.Property<string>("badi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bolumbskn")
                        .HasColumnType("int");

                    b.HasKey("bolumId");

                    b.HasIndex("bolumbskn");

                    b.ToTable("Bolumlers");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Ders", b =>
                {
                    b.Property<int>("dkod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dkod"), 1L, 1);

                    b.Property<string>("dadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dkod");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Notlar", b =>
                {
                    b.Property<int>("notId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notId"), 1L, 1);

                    b.Property<int>("dkod")
                        .HasColumnType("int");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<int>("final")
                        .HasColumnType("int");

                    b.Property<int>("no")
                        .HasColumnType("int");

                    b.Property<int>("vize")
                        .HasColumnType("int");

                    b.HasKey("notId");

                    b.HasIndex("dkod");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Ogrenci", b =>
                {
                    b.Property<int>("no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("no"), 1L, 1);

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bolumid")
                        .HasColumnType("int");

                    b.Property<bool>("cinsiyet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtar")
                        .HasColumnType("datetime2");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tcno")
                        .HasColumnType("int");

                    b.HasKey("no");

                    b.HasIndex("bolumid");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Aka_Ders", b =>
                {
                    b.HasOne("VYPS.Model2.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("dkod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VYPS.Model2.Models.Akademik", "Akademik")
                        .WithMany()
                        .HasForeignKey("pkod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Akademik");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Bolumler", b =>
                {
                    b.HasOne("VYPS.Model2.Models.Akademik", "Akademik")
                        .WithMany()
                        .HasForeignKey("bolumbskn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Akademik");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Notlar", b =>
                {
                    b.HasOne("VYPS.Model2.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("dkod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("VYPS.Model2.Models.Ogrenci", b =>
                {
                    b.HasOne("VYPS.Model2.Models.Bolumler", "Bolumler")
                        .WithMany()
                        .HasForeignKey("bolumid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolumler");
                });
#pragma warning restore 612, 618
        }
    }
}
